@startuml
title Add Token Success Flow
actor       TelegramUser as user
participant Bot as bot
participant Hub as hub
database    Database    as db
participant Auth as auth
participant GitHub as github

user -> bot : Chat ID, Token, TokenAlias
bot -> hub : Chat ID, Token, TokenAlias
hub -> auth: Validate token
auth -> github: Auth token
github --> auth: Auth response
auth --> hub: Auth response
hub -> db: Chat ID, Token, TokenAlias
hub --> bot: Chat ID, TokenAlias status
bot --> user: Chat ID, TokenAlias status
@enduml
